---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/types":
    post:
      summary: Creates a type
      tags:
      - Types
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: type
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      responses:
        '201':
          description: pet created
        '422':
          description: invalid request
  "/api/v1/types/{id}":
    get:
      summary: Retrieves a pet
      tags:
      - Pets
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: name found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required:
            - id
            - name
        '404':
          description: type not found
