---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/pizza_type":
    post:
      summary: Creates a type
      tags:
      - Pizza Types
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: type
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      responses:
        '201':
          description: type created
        '422':
          description: invalid request
    get:
      summary: Get All pizza types
      tags:
      - Pizza Types
      consumes:
      - application/json
      - application/xml
      responses:
        '200':
          description:
            description: Return all the available pizza types
  "/pizza_type/{id}":
    get:
      summary: Retrieves a pizza type by id
      tags:
      - Pizza Types
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: pizza type found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required:
            - id
            - name
        '404':
          description: type not found
